[[constraint]]
  name = "github.com/caarlos0/env"
  version = "3.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/ilijamt/envwrap"

[[constraint]]
  name = "github.com/oleiade/reflections"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true
